### ISSUE TITLE
Request for choice dropdown type field

### ISSUE THREAD

**Issue by Ladet02** [fabiocaccamo/django-extra-settings#12]
Can this be done? creating multiple choice from admin

**Comment by fabiocaccamo** [comment]
@Ladet02 this is a nice suggestion, surely it could be done, probably it will be harder than expected because many type of fields could support the choices.

Could you explain me your use case to understanding better the possible solutions?

**Comment by Ladet02** [comment]
Hmm, yes. That could work.
