### ISSUE TITLE
Bug view display value

### ISSUE THREAD

**Issue by fermenen** [fabiocaccamo/django-extra-settings#143]
**Python version**
3.10

**Django version**
5.0.3

**Package version**
0.12.0

**Current behavior (bug description)**

The list with all extra variables shows all possible VALUES and not the values for the particular type.

![cap1](https://github.com/fabiocaccamo/django-extra-settings/assets/32095133/0e6ae706-51a6-45dd-a559-a37b67c6de3c)

**Expected behavior**

![74425761-81325400-4e54-11ea-9095-3d64e1420bfe](https://github.com/fabiocaccamo/django-extra-settings/assets/32095133/315cb5f3-dbba-47da-9ed7-8743e1174fe5)

**Comment by fermenen** [comment]
Yes (collectstatic), I have also tried with anonymous window and nothing.

**Comment by fermenen** [comment]
@fabiocaccamo 
Effectively it is not in static neither the css nor the js, but in the collecstaric it does not pick them up.
![cap2](https://github.com/fabiocaccamo/django-extra-settings/assets/32095133/40158910-557b-4fed-889e-5344ee84c99d)
![cap3](https://github.com/fabiocaccamo/django-extra-settings/assets/32095133/4004ff29-ac81-4ab7-a54a-529487973a4e)

**Comment by fabiocaccamo** [comment]
@fermenen could you check if there are errors in the browser console please?

**Comment by fermenen** [comment]
Hello @fabiocaccamo, I had a bug with collecstatics, is resolved!
