### ISSUE TITLE
Feature to automatically delete old media files when file fields are updated or removed from admin

### ISSUE THREAD

**Issue by jonnyhoff** [fabiocaccamo/django-extra-settings#156]
**Is your feature request related to a problem? Please describe.**
When removing or updating files or images, the old files aren't removed.

**Describe the solution you'd like**
The files should be deleted after they are no longer needed.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-extra-settings/issues/156">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-extra-settings/issues/156/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-extra-settings/issues/156/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@jonnyhoff this is not an issue of this library, it's django's default behaviour. 
I suggest you to use [django-cleanup](https://github.com/un1t/django-cleanup).

**Comment by jonnyhoff** [comment]
You can use signals to add this feature.

**Comment by fabiocaccamo** [comment]
I know, but:
- it's out of scope for this library
- it would require more testing and maintenance
- the problem would be solved only for this app, I think it is safer to install another well-tested library that does this job exclusively
