### ISSUE TITLE
django.db.utils.ProgrammingError: relation "extra_settings_setting" does not exist

### ISSUE THREAD

**Issue by martibosch** [fabiocaccamo/django-extra-settings#167]
**Python version**: 3.11
**Django version**: 4.2.9
**Package version**: 0.12.0

**Current behavior (bug description)**: I followed the steps to add `django-extra-settings` from the README of this repo (see https://github.com/African-Cities-Lab/african-cities-lab-org/pull/92/files) and then used in some views (https://github.com/African-Cities-Lab/african-cities-lab-org/pull/93/commits/23ad00c70e67a3328294cce2088630510b897ead). After building my app, I get `django.db.utils.ProgrammingError: relation "extra_settings_setting" does not exist` when running initial migrations (see https://github.com/African-Cities-Lab/african-cities-lab-org/actions/runs/10720776358/job/29727764847).

**Expected behavior**: initial migrations should run seamlessly.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-extra-settings/issues/167">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-extra-settings/issues/167/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-extra-settings/issues/167/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@martibosch this application doesn't use relations (ForeignKey / ManyToMany), if you added a relation to the Setting model you should run `python manage.py makemigrations your_app` and `python manage.py migrate your_app`.

**Comment by martibosch** [comment]
Hello! I am sorry to reopen but I still get the same error when running `makemigrations`.

The bug can be reproduced by pulling from the [](https://github.com/African-Cities-Lab/african-cities-lab-org/tree/feat-openedx-sync) and running (see https://cookiecutter-django.readthedocs.io/en/latest/2-local-development/developing-locally-docker.html):

`docker compose -f local.yml build`
`docker compose -f local.yml up` (which will already fail)
`docker compose -f local.yml run --rm django python manage.py makemigrations "african_cities_lab.home"`

I actually do not need any relationship between a model and django-extra-settings, ideally I would like to use it just for the views/tasks. Is that possible? Otherwise, as a I workaround, I could try a model based approach if needed.

Thank you. Best,
Martí
