### ISSUE TITLE
Release 0.1.4 not available in pypi

### ISSUE THREAD

**Issue by obdulia-losantos** [fabiocaccamo/django-extra-settings#17]
The last release `0.1.4` is not available in pypi registry.

![image](https://user-images.githubusercontent.com/8459537/149809164-a57b351f-7297-4983-9cbc-1f861120be93.png)

**Comment by fabiocaccamo** [comment]
What do you say? It's available!! https://pypi.org/project/django-extra-settings/

Thank you for reporting this ;)
