### ISSUE TITLE
Bug: App fails to initialize when optional settings are not defined

### ISSUE THREAD

**Issue by jonnyhoff** [fabiocaccamo/django-extra-settings#177]
**Python version**
3.11.11

**Django version**
5.1.1

**Package version**
0.12.0

**Current behavior (bug description)**

The package crashes during Django app initialization when `EXTRA_SETTINGS_VERBOSE_NAME` is not defined in settings, with the following error:

```
AttributeError: 'Settings' object has no attribute 'EXTRA_SETTINGS_VERBOSE_NAME'
```

This occurs in `apps.py` where it directly accesses `settings.EXTRA_SETTINGS_VERBOSE_NAME` without providing a default value or checking for its existence.

**Expected behavior**

According to the package documentation, all settings should be optional. The app should initialize successfully without requiring `EXTRA_SETTINGS_VERBOSE_NAME` to be explicitly defined, either by:

1. Providing a default value using `getattr(settings, 'EXTRA_SETTINGS_VERBOSE_NAME', 'Extra Settings')`
2. Or handling the case when the setting is not defined

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-extra-settings/issues/177">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-extra-settings/issues/177/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-extra-settings/issues/177/pledge.svg">
</picture>
</a>

**Comment by jonnyhoff** [comment]
### Issue Resolution

The issue was resolved and turned out to be an initialization timing problem caused by Celery's task discovery configuration. 

#### Root Cause
When using Celery's `autodiscover_tasks` with `force=True`, it triggers an aggressive task discovery that accesses Django settings before they're fully initialized. This premature access prevents `django-extra-settings` from properly setting up its default configuration values.

#### Solution
Removing the `force=True` parameter from Celery's configuration allows Django's normal initialization sequence to complete, giving `django-extra-settings` time to properly initialize its default settings.

Before (causing the issue):
```python
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS, related_name='tasks', force=True)
```

After (working):
```python
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)
```
#### Suggestion
You might want to add a note in the documentation about potential initialization timing issues when using Celery with `force=True` in task discovery. This could help other users who might encounter similar issues.

Thanks for maintaining this package @fabiocaccamo! 🙌

**Comment by fabiocaccamo** [comment]
@jonnyhoff thank you very much for providing additional context, it may be useful to other people!

https://github.com/fabiocaccamo/django-extra-settings/blob/main/README.md#celery
