### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by belkka** [fabiocaccamo/django-extra-settings#2]
How to use extra settings? Is `Setting.get(name)` a "front-end" interface to access extra settings? (I have found it in the source code)
Are there any docs? It would be great to see usage description in README

**Comment by fabiocaccamo** [comment]
@belkka I updated the Usage section in the README: 
https://github.com/fabiocaccamo/django-extra-settings/blob/master/README.md#usage

**Comment by belkka** [comment]
Thanks!
