### ISSUE TITLE
Overriding Setting for a specific unit test

### ISSUE THREAD

**Issue by morlandi** [fabiocaccamo/django-extra-settings#20]
What is the suggested way to override a Setting for a specific unit test ?

Also (somehow related to the previous): is it possible/advisable to disable caching from settings when running unit tests?

Thank you

**Comment by fabiocaccamo** [comment]
Hello @morlandi 

1. Frankly I never did it, could you show me your test?
2. For doing this just set the `EXTRA_SETTINGS_CACHE_NAME` to a `DummyCache`: https://docs.djangoproject.com/en/4.0/topics/cache/#dummy-caching-for-development

**Comment by morlandi** [comment]
Hello @fabiocaccamo,
I regret I do not have a real snippet at hand, since I'm using django-constance in all my Django projects, and considering django-extra-settings as an interesting replacement.
I guess there are countless reasons for running unit tests with different values for a setting which will be modified at will by the site administrator.

I posted a few examples for django-constance some years ago to discuss of a little bug (then fixed) .. you might want to have a look at it to get an idea of what I'm talking about:

https://github.com/jazzband/django-constance/issues/151

**Comment by fabiocaccamo** [comment]
@morlandi I understand, so I think that an `override_setting` is what you would need, right?

**Comment by morlandi** [comment]
It's not a real need at the moment; I was just asking since I'm considering django-extra-settings for future projects.
You can safely close the issue.

**Comment by morlandi** [comment]
sure it is 😉 

P.S. are you coming at PyCon Italy 22 ?

**Comment by fabiocaccamo** [comment]
@morlandi this is possible by upgrading to `0.4.0` version. More info [here](https://github.com/fabiocaccamo/django-extra-settings#tests=).
