### ISSUE TITLE
Add ability to define initial settings with default values 

### ISSUE THREAD

**Issue by timomeara** [fabiocaccamo/django-extra-settings#21]
It would be super useful to be able to define an initial set of settings and values that would be available when an app is deployed.

The backend would be populated with the default data and available for modification in the admin UI

for example:
EXTRA_SETTINGS_INITIAL_VALUES = [
{'name': 'use_white_list', 'type': 'Setting.TYPE_BOOL',  'value': True},
{'name': 'white_list', 'type': 'Setting.TYPE_JSON',  'value': ['192.168.1.33', '127.0.0.1']},
{'name': 'use_black_list', 'type': 'Setting.TYPE_BOOL',  'value': False},
{'name': 'black_list', 'type': 'Setting.TYPE_JSON',  'value': []},
]

here's how constance does it:
[https://django-constance.readthedocs.io/en/latest/#configuration](https://django-constance.readthedocs.io/en/latest/#configuration)

**Comment by fabiocaccamo** [comment]
I think the best approach is to `get_or_create` some defaults defined in settings: `settings.EXTRA_SETTINGS_DEFAULTS`.

**Comment by InzGIBA** [comment]
You can currently use `Settings.get("VARIABLE_1", "DEFAULT_RESULT")`

Define "constants" and refer to them if necessary

**Comment by InzGIBA** [comment]
You can use the built-in functionality in the `get` method that the `Setting` model has. ([link](https://github.com/fabiocaccamo/django-extra-settings/blob/6882d94f364524861f535d959679698b810d49d8/extra_settings/models.py#L62))

And to avoid repetition of the "standard" function response, you can define as "constants" and refer to them in the project

**Comment by fabiocaccamo** [comment]
@timomeara this is possible by upgrading to `0.4.0` version. More info [here](https://github.com/fabiocaccamo/django-extra-settings#settings=).
