### ISSUE TITLE
Environment layer

### ISSUE THREAD

**Issue by InzGIBA** [fabiocaccamo/django-extra-settings#22]
I think the suggestion to add a new data layer has a place.

Case: When initializing a project, you can specify certain parameters in CI/CD and then override them in the database.

Code ([link](https://github.com/InzGIBA/django-extra-settings/commit/67bf0228b6c195e93e7fd459ba8054a90ac84d08)):

```
# shortcut
@staticmethod
def _get_from_env(name):
    return environ.get(name, None)

# updated method
@classmethod
def get(cls, name, default=None):
    val = cls._get_from_cache(name)
    if val is None:
        val = cls._get_from_database(name)
        if val is None:
            val = cls._get_from_env(name)
            if val is None:
                val = cls._get_from_settings(name)
                if val is None:
                    val = default
    return val
```

<a href="https://dashboard.polar.sh/fabiocaccamo/django-extra-settings/issues/22">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/fabiocaccamo/django-extra-settings/issues/22/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/fabiocaccamo/django-extra-settings/issues/22/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@InzGIBA 
- I agree with the possibility to define layers priority
- Reading from env variables could give some problems with types because all values would be strings, any idea?!

**Comment by InzGIBA** [comment]
There is a thought of splitting the model into several abstract models. Where in each one there will be a check depending on the type of value.

- If the variable type is "string", try converting in "__init__" (example)

Depending on external rule in settings, output traceback

**Comment by InzGIBA** [comment]
If you are interested in the idea, I can implement it in fork and send it to you for review

**Comment by fabiocaccamo** [comment]
@InzGIBA I'm not convinced about this approach, I would like to keep it very simple as it is now, I will think about this...

**Comment by InzGIBA** [comment]
How about integrating with the "EXTRA_SETTINGS_DEFAULTS" variable, where "value" is optional or will it be taken depending on the priority?

- from cache
- from database
- from env
- from default

But in the layer "env" there will be a check, if there is "env" and a value with the same "name" it will be checked, otherwise this layer will be skipped.

In the same way we can add a variable "EXTRA_SETTINGS_ENV_EXCEPT" - if the type conversion failed, it will print Exception, otherwise this value will be skipped.

Translated with www.DeepL.com/Translator (free version)

**Comment by fabiocaccamo** [comment]
@InzGIBA I changed my mind about this issue.

- Adding the possibility to change layers ordering would open the doors to many potential new issues when actually the current implementation covers the most part of the use cases, so I think that the effort is not repaid.

- Reading settings from env variables implies more work than expected because they are not typed, so I would suggest you to read env vars using `django-environ` so this package can access them as normal django settings.
