### ISSUE TITLE
Increase the size of the name and value_string fields in the model

### ISSUE THREAD

**Issue by lalvarezt** [fabiocaccamo/django-extra-settings#37]
**Is your feature request related to a problem? Please describe.**
I find that the current limit of 50 characters for the name and value_string fields in the model definition is restrictive. Currently are implemented as:

```
name = models.CharField(
    max_length=50,
    unique=True,
    verbose_name=_("Name"),
    help_text="(e.g. SETTING_NAME)",
)

value_string = models.CharField(blank=True, max_length=50, verbose_name=_("Value"))
```

It's true that we could use value_text instead of string but that one is multiline so that could be a problem

**Describe the solution you'd like**
Increase the size to a bigger value, I think that DB space is not a constraint here

```
name = models.CharField(
    max_length=255,
    unique=True,
    verbose_name=_("Name"),
    help_text="(e.g. SETTING_NAME)",
)

value_string = models.CharField(blank=True, max_length=255, verbose_name=_("Value"))
```

**Describe alternatives you've considered**
Local copy and override myself, but it would be nice it supported

**Comment by fabiocaccamo** [comment]
@lalvarezt it's a reasonable request.

**Comment by lalvarezt** [comment]
thanks for the quick update
