### ISSUE TITLE
Can not define global variables

### ISSUE THREAD

**Issue by Sinanaltundag** [fabiocaccamo/django-extra-settings#55]
**Python version**
3.10.7

**Django version**
4.1.1

**Package version**
0.7.0

**Current behavior (bug description)**
I install library as documentation and add default values
```
EXTRA_SETTINGS_DEFAULTS = [
    {
        "name": "AWS_STORAGE_BUCKET_NAME",
        "type": "string",
        "value": "my-bucket-name",
    }
]
```
But when I add these variables directly, it works
`AWS_STORAGE_BUCKET_NAME = "my-bucket-name"`

when I add a variable from admin panel, if same variable is at settings.py, give an error that same variable has been on settings.py so I think library recognize settings. 
I try both "EXTRA_SETTINGS_DEFAULTS" and "add values from admin panel" for different variables but it gives error that can not find values
![image](https://user-images.githubusercontent.com/87491141/209485122-e65db35f-3be9-47d1-ab3f-9845310fe2bd.png)
![image](https://user-images.githubusercontent.com/87491141/209485196-790a5cf6-0066-4587-8598-209cd242448b.png)
 
is it enough to do these for define global variables 
```
Run pip install django-extra-settings
Add extra_settings to settings.INSTALLED_APPS
Run python manage.py migrate
Run python manage.py collectstatic
Restart your application server
```
**Expected behavior**
Get global variables from database

<a href="https://dashboard.polar.sh/fabiocaccamo/django-extra-settings/issues/55">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/fabiocaccamo/django-extra-settings/issues/55/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/fabiocaccamo/django-extra-settings/issues/55/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@Sinanaltundag have you restarted your app server after having set `EXTRA_SETTINGS_DEFAULTS`. I'm not able to reproduce the issue.

**Comment by Sinanaltundag** [comment]
thanks for reply. I restarted my app but nothing change. I research and I think some variables defined only when app start like aws config and  not changable at runtime
https://docs.djangoproject.com/en/4.1/topics/settings/#altering-settings-at-runtime

**Comment by fabiocaccamo** [comment]
@Sinanaltundag could you submit a PR with a failing test?

**Comment by fabiocaccamo** [comment]
@Sinanaltundag I close this issue because it's stale, I will re-open it in case of activity.

**Comment by fabiocaccamo** [comment]
@Sinanaltundag there was a bug that affected `EXTRA_SETTINGS_DEFAULTS`, it has been fixed in the latest version.
