### ISSUE TITLE
Missing manage.py

### ISSUE THREAD

**Issue by belkka** [fabiocaccamo/django-extra-settings#6]
Test snippet in README suggests to run
```
python manage.py test --settings "tests.settings"
```
But there is no file named `manage.py` in the repo. I think either `manage.py` should be added, or README should be edited

_Originally posted by @belkka in https://github.com/fabiocaccamo/django-extra-settings/issues/4#issuecomment-642990944_

**Comment by fabiocaccamo** [comment]
This is a third-party library, you must use it in a django project that always has a `manage.py` file.

**Comment by belkka** [comment]
Is it supposed that one need to copy-paste files from the root of this repo to existing django project in order to run tests? Actually, django project does not necessary has a `manage.py` file or it can be edited to conform projects needs.

Looks like
```
python -m django --settings "tests.settings"
```
does the job. This is equivalent to running `manage.py` generated by default and it does not require creating a django project.

**Comment by fabiocaccamo** [comment]
@belkka it should be `python -m django test --settings "tests.settings"` ... anyway thank you for the suggestion, I will update the README.
