### ISSUE TITLE
False Image URL in Template

### ISSUE THREAD

**Issue by aztecrabbit** [fabiocaccamo/django-extra-settings#9]
**Python version**
Python 3.8.5

**Django version**
Django 3.1.5

**Package version**
django-extra-settings 0.1.2

**Current behavior (bug description)**
```
MEDIA_URL = '/media/'
EXTRA_SETTINGS_IMAGE_UPLOAD_TO = 'images'
```

`{% get_setting 'SITE_LOGO' %}` return `images/logo.png`

**Expected behavior**

`{% get_setting 'SITE_LOGO' %}` return `media/images/logo.png`

**Comment by aztecrabbit** [comment]
Or i must use like this?

```
{{ MEDIA_URL }}{% get_setting 'SITE_LOGO' %}
```

**Comment by fabiocaccamo** [comment]
@aztecrabbit `get_setting` returns the image field (which could have not a file), so in your case you should do:
```python
{% get_setting 'SITE_LOGO' as site_logo %} 
{% if site_logo %}{{ site_logo.url }}{% endif %}
```
